let num1 = Number(prompt(" balinizi daxil edin"))
let num2 = Number(prompt(" balinizi daxil edin"))
let num3 = Number(prompt(" balinizi daxil edin"))
let num4 = Number(prompt(" balinizi daxil edin"))
let num5 = Number(prompt(" balinizi daxil edin"))
let fenn=parseInt((num1+num2+num3+num4+num5)/5)
console.log(fenn)